### ISSUE TITLE
License/Citation information missing

### ISSUE THREAD

**Issue by sraimund** [arnofiva/world-sizes#1]
You have build a nice tool for educative purposes!

Could you please add some license information for reuse?
In particular, is it ok to take screenshots for scientific publications (with attribution)?

**Comment by arnofiva** [comment]
Thanks for your feedback and pointing out the missing licensing. We generally release our public Esri demos under the Apache license which should be flexible enough for your purpose. I've just added the license information to the repository, thanks!
